
[[Task]]
name = "test"
src = "/home/inimei/workspace/inimei"
files = ["tmp", ".git", ".vscode", ".bundle", ".idea", "vendor"]
content = true
dest = "/home/inimei/tmp"
sync = false
log2file = true # 是否输出日志文件
count = 2 #保留的备份天数
